spring:
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false
    open-in-view=true:server: true
  port: 8081 # This is the default port anyway, but you can change it here

fixedDelay:
  in:
    milliseconds: 20000
demo:
  body: This is the message, I am tring to reach out, I hoper you

